- name: install system commands
  apt:
    name:
      - etckeeper
      - git
      - git-lfs
      - curl
      - tree
      - xclip
      - xsel
      - mlocate
      - htop
      - direnv
      - cmake
      - g++
    state: present # NOTE: if not installed, install

- import_tasks: commands/btm.yaml
