- name: install system commands
  apt:
    name:
      - etckeeper
      - git
      - git-lfs
      - curl
      - tmux
      - tree
      - xclip
      - xsel
      - mlocate
      - htop
      - direnv
    state: present # NOTE: if not installed, install
