- name: setup docker
  block:
    # apt
    - block:
      - name: get gpg key
        ansible.builtin.get_url:
          url: https://download.docker.com/linux/ubuntu/gpg
          dest: /etc/apt/keyrings/docker.asc
          mode: '0644'

      - name: add repo
        copy:
          dest: /etc/apt/sources.list.d/docker.sources
          content: |
            Types: deb
            URIs: https://download.docker.com/linux/ubuntu
            Suites: {{ ansible_distribution_release }}
            Components: stable
            Signed-By: /etc/apt/keyrings/docker.asc

      - name: install docker on baremetal
        apt:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-buildx-plugin
            - docker-compose-plugin
          state: present
          update_cache: true
        when: is_baremetal

      - name: check docker installability on ci
        apt:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-buildx-plugin
            - docker-compose-plugin
          state: present
          update_cache: true
        when: not is_baremetal
        check_mode: true

    # setup docker group
    - block:
      - name: get username
        become: false # if true, `whoami` returns root
        ansible.builtin.command: whoami
        register: username
        failed_when: username.rc != 0
        changed_when: false

      - name: add docker group
        ansible.builtin.group:
          name: docker
          state: present

      - name: check and save if user belongs to docker group
        ansible.builtin.shell: id -nG {{ username.stdout }}
        register: user_groups
        changed_when: false

      - name: add user to docker group
        user:
          name: "{{ username.stdout }}"
          groups: docker
          append: true # "-aG"

      - name: prompt logout
        debug:
          msg: "Please logout once to use docker"
        when: "'docker' not in user_groups.stdout.split()" # "" is necessary

- name: check nvidia-smi
  shell: command -v nvidia-smi >/dev/null 2>&1
  register: nvidia_smi_exists
  failed_when: false

- name: setup nvidia-container
  when: nvidia_smi_exists.rc == 0
  block:
    - name: add gpg key
      shell:
        cmd:
          "curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list"
        creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: install nvidia-container-toolkit
      ansible.builtin.apt:
        name:
          - nvidia-container-toolkit={{ NVIDIA_CONTAINER_TOOLKIT_VERSION }}
          - nvidia-container-toolkit-base={{ NVIDIA_CONTAINER_TOOLKIT_VERSION }}
          - libnvidia-container-tools={{ NVIDIA_CONTAINER_TOOLKIT_VERSION }}
          - libnvidia-container1={{ NVIDIA_CONTAINER_TOOLKIT_VERSION }}
        state: present
        update_cache: true

    - name: configure
      shell: nvidia-ctk runtime configure --runtime=docker && systemctl restart docker
