- name: install gui tools on baremetal
  - block:
      apt:
        name:
          - vlc
          - simplescreenrecorder
          - gparted
        state: present
      when: is_baremetal

  - block:
      community.general.snap:
        name:
          - flameshot
        state: present
        classic: yes
      when: is_baremetal

- name: check gui tools installability on ci
  - block:
      apt:
        name:
          - vlc
          - simplescreenrecorder
          - gparted
        state: present
      when: not is_baremetal
      check_mode: true

  - block:
      community.general.snap:
        name:
          - flameshot
        state: present
        classic: yes
      when: not is_baremetal
      check_mode: true
