- name: install gui tools on baremetal
  apt:
    name:
      - vlc
      - simplescreenrecorder
      - gparted
    state: present
  when: is_baremetal

- name: check gui tools installability on ci
  apt:
    name:
      - vlc
      - simplescreenrecorder
      - gparted
    state: present
  when: not is_baremetal
  check_mode: true
