- name: install gui tools on baremetal
  block:
    - apt:
        name:
          - vlc
          - simplescreenrecorder
          - gparted
        state: present
      when: is_baremetal

    - community.general.snap:
        name:
          - flameshot
        state: present
        classic: true
      when: is_baremetal

- name: check gui tools installability on ci
  block:
    - apt:
        name:
          - vlc
          - simplescreenrecorder
          - gparted
        state: present
      when: not is_baremetal
      check_mode: true

    - community.general.snap:
        name:
          - flameshot
        state: present
        classic: true
      when: not is_baremetal
      check_mode: true
