- hosts: localhost
  become: true
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ lookup('env','HOME') }}/.local/bin"
  roles:
    - init_snap
    - xdg_base_directory
    - dot_rc
    - system_tools
    - dev_tools
    - fonts
    - gui_tools
