[general]
import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]

[terminal]
# this is not good on some environment, because ".bashrc" is not sourced as bash
# shell = { program = "fish", args = ["--login"]}

[window]
opacity = 0.84

[font]
normal = { family = "HackGen Console NF", style = "regular"}
size = 12
builtin_box_drawing = true
